name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Build ignition config from butane yaml
      - name: Ignition Server
        run: docker run --interactive --rm quay.io/coreos/butane:release --pretty --strict < server.yaml > server.ign
      - name: Ignition Server2
        run: docker run --interactive --rm quay.io/coreos/butane:release --pretty --strict < server2.yaml > server2.ign
      - name: Ignition Pie1
        run: docker run --interactive --rm quay.io/coreos/butane:release --pretty --strict < pie1.yaml > pie1.ign

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            server.ign
            server2.ign
            pie1.ign
          commit-msg: Update config ign
          github-token: ${{ secrets.GITHUB_TOKEN }}
